### ISSUE TITLE
Latest devtools (2.0.1) breaks the package build process

### ISSUE THREAD

**Issue by jrawbits** [gregorbj/VisionEval#207]
Apparently, with the update to devtools 2.0.1, the "use_data" function which is used heavily throughout the VE modules is now terminally broken.  The "use_data" function now resides (only) in the package "usethis".  So the modules will build again under devtools 2.0.1 if you change all occurrences of "devtools::use_data" to "usethis::use_data" and then replace (since use_data is the only thing devtools is used for inside the packages) the devtools dependency with a usethis dependency.

**Comment by gregorbj** [comment]
use_data is used throughout modules for saving models when packages are built. It would be fairly simple to go through the modules, find the function call and replace devtools::use_data with usethis::use_data. It's disappointing that an approach recommended by Hadley Wickham in "R Packages" is now broken. Is there a way to handle this in base R so that we don't need to rely on devtools or usethis. Perhaps it's better to make the change and hope that something else won't be changed in the future that will interfere with something as basic as building the VE packages.

**Comment by jrawbits** [comment]
They’ve just moved on – I think it’s part of separating stuff you need inside a package (use_data) from stuff you need to develop a package (build, install).  I was able to get it all to compile just by doing the global search and replace I described in the original issue:
  devtools::use_data => usethis::use_data
and then replacing the dependency on “devtools” with a dependency on “usethis”.

You can visit my test repository (VisioneEval-JR) and look at the diff between the “devtools-2.0.1” branch and the “master” branch.  My master branch is probably physically identical (right down to the commits) to what is in gregorbj/visioneval master, so you might get away with setting mine as a remote and checking out just the “devtools-2.0.1” branch from it which you could then merge onto your own master).  I would have done a pull request, but I’m forked off the visioneval organization visioneval-dev repository…

**Comment by goreaditya** [comment]
> 
> 
> use_data is used throughout modules for saving models when packages are built. It would be fairly simple to go through the modules, find the function call and replace devtools::use_data with usethis::use_data. It's disappointing that an approach recommended by Hadley Wickham in "R Packages" is now broken. Is there a way to handle this in base R so that we don't need to rely on devtools or usethis. Perhaps it's better to make the change and hope that something else won't be changed in the future that will interfere with something as basic as building the VE packages.

The only way this can be handled in base R is by saving the data manually by calling `save(varname, file = file.path("data", paste0(varname, ".rda")))`, which is what devtools and usethis packages call internally after performing several other operations.

**Comment by jrawbits** [comment]
I don’t think there’s any reason to revert immediately to base R in this case.  Changing the dependency in the packages to “usethis” (rather than devtools) and globally replacing “devtools::use_data” with “usethis::use_data” works just fine.

**Comment by gregorbj** [comment]
I'll make the changes from devtools:use_data to usethis::use_data in the develop branch. I've got some other changes to make there.

**Comment by dflynn-volpe** [comment]
This seems to be breaking the install.R as well -- was trying a clean install to test out VEGUI, and had this error in VE2001NHTS:

```
Installing package into ‘C:/Users/daniel.flynn.ctr/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'VE2001NHTS' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Warning: 'devtools::use_data' is deprecated.
Use 'usethis::use_data()' instead.
See help("Deprecated") and help("devtools-deprecated").
<U+2714> Setting active project to 'C:/Users/daniel.flynn.ctr/AppData/Local/Temp/1/RtmpAXbJTp/R.INSTALL29d44b7311af/VE2001NHTS'
<U+2714> Saving 'Hh_df' to 'data/Hh_df.rda'
Error in (function (..., list = character(), file = stop("'file' must be specified"),  : 
  object 'Hh_df' not found
Error : unable to load R code in package 'VE2001NHTS'
ERROR: lazy loading failed for package 'VE2001NHTS'
* removing 'C:/Users/daniel.flynn.ctr/Documents/R/win-library/3.5/VE2001NHTS'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/DANIEL~1.CTR/AppData/Local/Temp/1/Rtmp8gxAE7/file327c79b823/VE2001NHTS_0.9.tar.gz’ had non-zero exit status
```

**Comment by landisrm** [comment]
@dflynn-volpe this issue should be resolved on the add_scenario branch.  Make sure your install script is pointing to add_scenario.

**Comment by dflynn-volpe** [comment]
Thanks Matt, you are right -- manually setting `ref <- "add_scenario"` in the install.R works. 
Got all the way to Run Model Script step for VERPAT_Scenarios or BaseYearVERPAT, 
![image](https://user-images.githubusercontent.com/9107903/48573646-e0648a00-e8da-11e8-994f-93e5b039d50d.png)

and then get 
```
 "2018-11-15 13:31:54: ***ERROR*** processRunningTasks: 'CAPTURED_SOURCE' returned an error: Error in readModelState(): object 'State_ls' not found\n"
```

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
```

**Comment by landisrm** [comment]
What did you select for the run_model.R script?  Currently VEGUI can only work with VERPAT/run_model.R or VERSPM/Test1/run_model.R.  It hasn't been tested with VERPAT_Scenarios.

**Comment by dflynn-volpe** [comment]
I tried  VERPAT_Scenarios and BaseYearVERPAT, now I've tried VERPAT/run_model.R and VERSPM/Test1/run_model.R, and am getting the same error message.

Here's what's weird: I do the following
```
rm(list=ls())
library(visioneval)
runApp('../VEGUI')
```
And get the same error. However,  `ModelState_ls` does get created and exists in my global environment, and readModelState() still fails even outside the app:

```
> readModelState()
Error in readModelState() : object 'State_ls' not found
> ls()
 [1] "asyncTasksRunning"       "fakeDataProcessing"      "file.info"               "fileGetter"              "getNumberOfRunningTasks"
 [6] "getRunningTasksStatus"   "ModelState_ls"           "processRunningTasks"     "startAsyncTask"          "testAsync"              
> readModelState
function (Names_ = "All", FileName = "ModelState.Rda") 
{
    if (file.exists(FileName)) {
        load(FileName)
    }
    if ("ModelState_ls" %in% ls()) 
        State_ls <- get("ModelState_ls")
    if (Names_[1] == "All") {
        return(State_ls)
    }
    else {
        return(State_ls[Names_])
    }
}
<bytecode: 0x00000000171fb770>
<environment: namespace:visioneval>
```

Something funny is going on, because I can run `State_ls <- get("ModelState_ls")` just fine, and then readModelState works. One thing to try (I'm out of time today, but can try later) is make the following change from
```
if ("ModelState_ls" %in% ls()) State_ls <- get("ModelState_ls")
```
to
```
if ("ModelState_ls" %in% ls()) {
 State_ls <- get("ModelState_ls")
}
```
While it shouldn't really matter, having three if statements in a row where the middle one is not in curly braces might be the culprit.

**Comment by jrawbits** [comment]
Note that you still have devtools as an extraneous dependency in the DESCRIPTION files for the packages.  Beyond "use_data", no other devtools function is required to build the packages, so it should probably be eliminated.
